use college_system;


CREATE TABLE COURSE_FACULITY (
    FACCODE VARCHAR(5),
    CCODE VARCHAR(5),
    GRADE CHAR(1),
    PRIMARY KEY (FACCODE, CCODE),
    CONSTRAINT CHK_GRADE CHECK (GRADE IN ('A', 'B', 'C'))
);

insert into COURSE_FACULITY(FACCODE, CCODE, GRADE) VALUES
('F001', 'C002', 'A'),
('F002', 'C001', 'B'),
('F003', 'C003', 'C'),
('F004', 'C005', 'A'),
('F005', 'C004', 'B');

SELECT * FROM COURSE_FACULITY;